#!/bin/bash
# Build LaTeX templates into JavaScript for SwiftLaTeX browser compilation
# This script reads all .tex files and creates a JS file with them embedded

cd "$(dirname "$0")/.."

OUTPUT="web/js/latex-templates.js"

echo "/**" > "$OUTPUT"
echo " * LaTeX Templates for SwiftLaTeX Browser Compilation" >> "$OUTPUT"
echo " * Auto-generated by build-templates.sh - DO NOT EDIT" >> "$OUTPUT"
echo " * Generated: $(date)" >> "$OUTPUT"
echo " */" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "const LATEX_TEMPLATES = {" >> "$OUTPUT"

# Add main.tex from tex/
echo "  'tex/main.tex': \`" >> "$OUTPUT"
cat tex/main.tex | sed 's/\\/\\\\/g' | sed 's/`/\\`/g' | sed 's/\$/\\$/g' >> "$OUTPUT"
echo "\`," >> "$OUTPUT"

# Add template files from tex/templates/
echo "" >> "$OUTPUT"
echo "  // Template files" >> "$OUTPUT"
for file in tex/templates/*.tex; do
    name=$(basename "$file")
    echo "  'tex/templates/$name': \`" >> "$OUTPUT"
    cat "$file" | sed 's/\\/\\\\/g' | sed 's/`/\\`/g' | sed 's/\$/\\$/g' >> "$OUTPUT"
    echo "\`," >> "$OUTPUT"
done

echo "};" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "// Export for use in app.js" >> "$OUTPUT"
echo "if (typeof window !== 'undefined') {" >> "$OUTPUT"
echo "  window.LATEX_TEMPLATES = LATEX_TEMPLATES;" >> "$OUTPUT"
echo "}" >> "$OUTPUT"

echo "Generated $OUTPUT with $(grep -c "'.*/.*':" "$OUTPUT") template files"
